= Travaux pratiques - SonarQube
Nicolas Frankel
:doctype: article
:encoding: utf-8
:lang: fr
:toc:
:toc-placement!:
:numbered:
:experimental:
:sectanchors:
:icons: font
:imagesdir: images/vcs

include::../common/license.adoc[]

toc::[]

== Objectif

L'objectif de cette fiche est de paramétrer un projet Maven pour lancer une analyse SonarQube et envoyer les résultats à un serveur Sonar.

== Références

En anglais: ::
+
* http://docs.sonarqube.org/display/SCAN/Analyzing+with+SonarQube+Scanner+for+Maven[Analyzing with SonarQube Scanner for Maven^]
* https://about.sonarcloud.io/[SonarCloud^]

== SonarCloud

SonarCloud est une offre de SonarSource qui propose une offre Sonar en mode _Software-as-a-Service_.

NOTE: Pour un projet dont le code source est libre, la fonctionnalité est gratuite.

* Aller sur l'interface https://about.sonarcloud.io/[SonarCloud]
* Cliquer sur le lien btn:[Sign in] en haut à droite
* Sélectionner btn:[Configure & Sign up]
* Suivre les étapes proposées

== Sonar local

Il est nécessaire de disposer d'un serveur SonarQube local.

Pour cela, il est possible de télécharger le logiciel pour lancer une instance locale.

* Télécharger la http://www.sonarqube.org/downloads/[dernière version de SonarQube]
* Décompresser l'archive
* Lancer SonarQube
+
[source,bash]
----
$SONAR_QUBE_HOME/bin/[OS]/sonar.sh start
----
+
[WARNING]
====
Sans configuration plus poussée, la base de données utilisée par défaut est http://www.h2database.com/html/main.html[H2], qui n'est pas destinée à un usge en production.
====

=== Lancement de l'analyse SonarQube

Configurer le POM pour disposer de la dernière version du plugin SonarQube pour Maven.

Puis, pour lancer l'analyse SonarQube, exécuter la commande suivante dans le répertoire du projet :

[source,bash]
----
mvn sonar:sonar
----

Par défaut, l'analyse est envoyée au serveur SonarQube local.

=== Consultation des résultats

Les résultats sont disponibles à http://localhost:9000.

Corriger les violations par ordre de priorité, re-lancer l'analyse. Répéter autant de fois que nécessaire.